---

language: python
dist: focal
python:
  - 3.7
services: docker

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS: 1
  matrix:
    - MOLECULE_DOCKER_IMAGE: centos:6
    - MOLECULE_DOCKER_IMAGE: centos:7
    - MOLECULE_DOCKER_IMAGE: centos:8
    - MOLECULE_DOCKER_IMAGE: debian:jessie
    - MOLECULE_DOCKER_IMAGE: debian:stretch
    - MOLECULE_DOCKER_IMAGE: debian:buster
    - MOLECULE_DOCKER_IMAGE: ubuntu:xenial
    - MOLECULE_DOCKER_IMAGE: ubuntu:bionic
    - MOLECULE_DOCKER_IMAGE: ubuntu:focal
    - MOLECULE_DOCKER_IMAGE: ubuntu:latest

install:
  - pip install pipenv
  - pipenv install --skip-lock

jobs:
  include:
    - script:
        - pipenv run test
      env: MOLECULE_DOCKER_IMAGE=ubuntu:latest

script:
  - pipenv run test -s tagged

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
