---

language: python
python:
  - 3.7
services: docker

env:
  matrix:
    - MOLECULE_DOCKER_IMAGE: centos:6
    - MOLECULE_DOCKER_IMAGE: centos:7
    - MOLECULE_DOCKER_IMAGE: centos:8
    - MOLECULE_DOCKER_IMAGE: debian:jessie
    - MOLECULE_DOCKER_IMAGE: ubuntu:xenial
    - MOLECULE_DOCKER_IMAGE: ubuntu:bionic

install:
  - pip install pipenv
  - pipenv install --skip-lock

script:
  - pipenv run test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
