---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_DOCKER_IMAGE:-ubuntu:latest}
provisioner:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
verifier:
  name: testinfra
