---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:bionic
provisioner:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
verifier:
  name: testinfra
